apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ParentInfoCluster
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Ensure secrets are created before the cluster on ArgoCD
  namespace: parentinfo
spec:
  description: "CNPG Cluster for Parent Info Application"
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 3
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: app # Initial database name
      owner: app # Owner of the initial database
      secret:
        name: cnpg-app-user

  enableSuperuserAccess: true
  superuserSecret:
    name: cnpg-super-user

  storage:
    storageClass: longhorn-xfs # Specify your storage class here, e.g., longhorn-xfs, nfs-client, etc.
    size: 1Gi

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"
