"""
Django settings for parentinfo project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.core.management.utils import get_random_secret_key

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

allowed_hosts_string = os.environ.get('DJANGO_ALLOWED_HOSTS') 
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_string.split(',')]

# ----- CSRF trusted origins -----
allowed_csrf_string = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS')
CSRF_TRUSTED_ORIGINS = [host.strip() for host in allowed_csrf_string .split(',')]

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'activity',
    'core',
    'dashboard',
    'announcement',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'parentinfo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'parentinfo.wsgi.application'

# -------- Cloudflare R2 for static and media files -------------- #
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL")  # https://<account_id>.r2.cloudflarestorage.com
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "auto")
AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN")

# Special parameters For Cloudflare R2
AWS_S3_ADDRESSING_STYLE = "virtual"      
AWS_DEFAULT_ACL = None                    
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_QUERYSTRING_AUTH = False            

# Stream for big files
#AWS_S3_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Optional: sensible default object parameters (cache headers) for static/media
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400, must-revalidate",
}

# NOTE: We keep storage classes in a separate module to avoid importing boto3
# (and django-storages) at settings-import time which can break some manage.py
# commands in environments where those packages are not installed.
STORAGES = {
    "default": {
        "BACKEND": "parentinfo.storages.MediaStorage",
    },
    "staticfiles": {
        "BACKEND": "parentinfo.storages.StaticStorage",
    },
}

# Build STATIC_URL / MEDIA_URL safely: prefer a custom domain, fall back to the
# R2 endpoint, and finally to local paths if neither is provided.
STATIC_DOMAIN = AWS_S3_CUSTOM_DOMAIN or AWS_S3_ENDPOINT_URL
if STATIC_DOMAIN:
    STATIC_DOMAIN = STATIC_DOMAIN.rstrip('/')
    STATIC_URL = f"https://{STATIC_DOMAIN}/static/"
    MEDIA_URL = f"https://{STATIC_DOMAIN}/media/"
else:
    STATIC_URL = "/static/"
    MEDIA_URL = "/media/"

# ---------- Database Configuration for PostgreSQL -------------- #
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("PG_DB"),
            'USER': os.getenv("PG_USER"),
            'PASSWORD': os.getenv("PG_PASSWORD"),
            'HOST': os.getenv("PG_HOST"),
            'PORT': os.getenv("PG_PORT")
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
