# Generated by Django 5.2.6 on 2025-10-26 19:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='İsim')),
                ('notice', models.TextField(verbose_name='Announcement')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcement/', verbose_name='Resim')),
                ('time', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'General Announcement',
                'verbose_name_plural': 'Genaral Announcements',
                'ordering': ['-time'],
                'get_latest_by': 'time',
            },
        ),
        migrations.CreateModel(
            name='InstitutionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instutionnotice', models.TextField(verbose_name='Program schedule, additional announcement information, announcements:')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_notice', to='core.institution', verbose_name='Institution')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_notice', to='announcement.generalnotice', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Institution Announcement',
                'verbose_name_plural': 'Institution Announcements',
                'ordering': ['-name'],
            },
        ),
    ]
