# Generated by Django 5.2.6 on 2025-10-26 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Institution Name')),
                ('address', models.CharField(max_length=200, verbose_name='Institution Address')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location (Google Maps link or address)')),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_institution', to=settings.AUTH_USER_MODEL, verbose_name='Institution Admin')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['name'],
                'get_latest_by': 'name',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Student First Name')),
                ('last_name', models.CharField(max_length=80, verbose_name='Student Last Name')),
                ('grade', models.CharField(choices=[('5', '5. Grade'), ('6', '6. Grade'), ('7', '7. Grade'), ('8', '8. Grade')], max_length=200, verbose_name='Student Academic Grade')),
                ('level', models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3')], max_length=200, verbose_name='Student Social Level')),
                ('status', models.BooleanField(default=True, verbose_name='Is student active ?')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.institution', verbose_name='Institution')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['first_name'],
                'get_latest_by': 'first_name',
            },
        ),
    ]
