apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-super-user
  namespace: parentinfo
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    password: AgB7Gqy/ucuhZ9Gg4y9oQKamVdk2aPfBo5B5p/QI6FiHwiKjyT4qEagLk/9igvUI72qx96jDFryVB8M79lIqo70yyObvXHWBHsphMpaJH7uA60j7LAh7i2F8qhHjwNt6mJ/y8aeiYaaSM1cIk9gzGriXZwTxLv5XwOb+0DPrQe4HXF0LiUweMyNRuanQtdoDRJViOwiA11E9jRAvze5Z/yn8dp8KzTVfChfMjgQUH/01h94PW1Eg41lEsskZGdwkDCtbuIoqUbwmP2KZFsNW0uVvhZeKWPp2CSq4OKvdcZeH19M2HxP8dCYNmwFb/9LyHcJUc7P+nBLmtYrIHIPpLu2FmGBJLBKwo15reQn9LNT4qYEwn9bv0gobgvWEbpfkIWLz4n2G3ieIYcrg2HGFI+rReptCAZs8oCpvcajiMU65XemXJQUunT/thOztboN/TF9GxhIHLrRsiqEQu0ybKZPgo3DOIpIRpkwfZY9nl9/N0Vvpd7GW4Wl3cfoP1m64j991oXMiG3iwnGYTvdeXzKJWKVog1rUNDG/59aHulmvbUlCJKINcHvqU4pPVXmE2NEjHptYRZgMCIv1qbhDxPcmrdk34SxEwDI1fvW+tGyISkyeRHlrtjsr0Vzygn5VuUkFIVtnx+wITs634UVRT9SYagz0wIp9WOhuNo0KNulbSYsTRz3mpmkAdjAP2C0t9h2DDD47e3x4yw8zmTF8=
    username: AgBmXyKWhCsU271j+H07HC8uj/W2EDc+y1Q+NgKtyleo31ZxSVs1/ZNDwZX1uLflS//v+eagUGyagj3ncsD8yV0R+BLppvNj/cs1nchd3NbJfc6MgxMhXcjpaovtBkZh19uQT4ywPTE427xdxfAeN2yhtsM+MTGGMgChzZldzE2ECP2GElX6gWQCpQEpxTuxLPjiwEY0TOD/Bripkf3LR+TguSueZOfbNQ2TXB5HQRPxY6s7ezeq4acJtIJrFOoNmNbDBVu2Q61C+7VmunGsfR8Kwf+WKtwhc0Y19X63/xHllYwFcs90ZD+0H2x350w4uly0Bv/4XInspqZKTUAmmuk5Jl7kuGx9BuFvb1DTiMilaSXGssBFDUHxV9uCN03YVcer5NfXqricbabVDktfGmZuevsxp7DGKfZcUsuD6u1eVBDlq7cWpfoXx0sjpzXmlm5G3gZslTIJXVaYue9y6zRz7cAahA3r0/EwfqNNW6Qw3AcY0r+c6loTwv2qD/GxXhKHt+lLaVY34uoS1cW99dnKxOGXk7CAUNErYPh+j+TLlX3K1FcEt+WxCvHQicgmtXv+fSKORtj0axscJqL3i0qpuz3La2nfJ+9MZHsSBcpIBQLWK1tTkujhi33glmU9X2t5xT8+knMJ/dM0LztVW9PBn29ekYQSRBBWqOUOOT7WI2/e/QK7ipeSPdky4Cv9JBvE2QZe+vsvrw==
  template:
    metadata:
      name: cnpg-super-user
      namespace: parentinfo
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"