# Generated by Django 5.2.6 on 2025-10-26 19:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('5', '5. Grade'), ('6', '6. Grade'), ('7', '7. Grade'), ('8', '8. Grade')], max_length=200, verbose_name='Grade')),
                ('description', models.TextField(verbose_name='Academic activity description')),
                ('time', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.institution')),
            ],
            options={
                'verbose_name': 'Academic Activity',
                'verbose_name_plural': 'Academic Activities',
                'ordering': ['-time', 'grade'],
                'get_latest_by': 'time',
            },
        ),
        migrations.CreateModel(
            name='LevelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3')], max_length=200, verbose_name='Level')),
                ('description', models.TextField(verbose_name='Social Activity')),
                ('time', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='levels/', verbose_name='Image')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='core.institution')),
            ],
            options={
                'verbose_name': 'Social Activity',
                'verbose_name_plural': 'Social Activities',
                'ordering': ['-time', 'level'],
                'get_latest_by': 'time',
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_year', models.PositiveIntegerField(default=2025)),
                ('iso_week', models.PositiveIntegerField(default=43)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='core.student', verbose_name='Student')),
            ],
        ),
    ]
