name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push-docker-image:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/ruchany13/parentinfo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set Image Tag
      id: vars
      run: echo "IMAGE_TAG=$(date +'%s')" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Docker/Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the Docker image
      run: docker push $IMAGE_NAME:$IMAGE_TAG
    
    - name: Output image details
      run: |
        echo "Docker Image: $IMAGE_NAME:$IMAGE_TAG" 
    
    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq
    - name: Update Kubernetes deployment file with new image tag
      run: |
        yq e '.spec.template.spec.containers[0].image = "'$IMAGE_NAME':'$IMAGE_TAG'"' -i Kubernetes/demo/parentinfo-app/Deployment.yaml

          - name: Commit and push changes
            run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add Kubernetes/demo/parentinfo-app/Deployment.yaml
         
            if git diff --cached --quiet; then
              echo "No changes to commit."
            else
              git commit -m "Update image tag to $IMAGE_TAG"
              git push origin main
            fi